repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: ["--fix=no"]
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        require_serial: true
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        require_serial: true
